import { quizChallenge, type QuestTemplate } from './framework.js';

/**
 * Logic + puzzle pools — deduction with fully worked reasoning, and technical
 * brainteasers with checkable answers.
 */

export const logicTemplates: QuestTemplate[] = [
  quizChallenge({
    id: 'logic.two-ropes',
    category: 'logic',
    challengeType: 'logic_puzzle',
    difficulty: 'intermediate',
    minutes: 15,
    concepts: ['rate reasoning'],
    tags: ['classic'],
    skills: ['Constraint manipulation'],
    subcategories: ['deduction'],
    title: 'The Uneven Ropes',
    subtitle: 'Two fuses, one measurement, forty-five minutes.',
    description: 'The classic: measure 45 minutes with two non-uniform hour ropes.',
    question:
      'You have two ropes. Each takes exactly 60 minutes to burn completely, but they burn NON-uniformly (half the length can take any fraction of the time). You also have a lighter. How do you measure exactly 45 minutes?',
    options: [
      'Light rope A at both ends and rope B at one end simultaneously; when A finishes, light B’s other end — B finishes 15 minutes later',
      'Fold each rope in half and burn the halves simultaneously',
      'Cut rope A in half and burn both halves at the same time',
      'Light both ropes at one end and wait for the difference',
    ],
    optionExplanations: [
      'Correct: A burning from both ends finishes in 30 min regardless of non-uniformity; at that moment B has 30 min of burn left, and lighting its second end halves that to 15 → 30 + 15 = 45.',
      'Folding is meaningless for non-uniform ropes — the fold point says nothing about burn time.',
      'Same flaw: the two half-lengths burn at unknown rates.',
      'That measures the DIFFERENCE of burn times, which is zero here — both are 60-minute ropes.',
    ],
    reasoning: [
      'Key insight 1: burning both ends halves the remaining time whatever the rope’s shape, because the two flames together consume 2× the rate.',
      'Key insight 2: at minute 30, rope B has exactly 30 minutes of fuel left.',
      'Lighting B’s other end then doubles its consumption rate again → 15 more minutes.',
    ],
    hints: ['What total burn rate do two flames on one rope achieve?', 'The 45 must decompose as 30 + 15.'],
    objectives: ['Reason with rates instead of lengths', 'Decompose target times into measurable chunks'],
  }),

  quizChallenge({
    id: 'logic.guard-question',
    category: 'logic',
    challengeType: 'logic_puzzle',
    difficulty: 'intermediate',
    minutes: 12,
    concepts: ['double negation'],
    tags: ['classic'],
    skills: ['Truth-table reasoning'],
    subcategories: ['deduction'],
    title: 'The Two Guards',
    subtitle: 'One question, two liars... or one.',
    description: 'The classic one-question truth/lie riddle with the compositional trick.',
    question:
      'Two doors: one leads out, one leads to doom. One guard always lies, one always tells the truth, and you do not know which is which. You may ask ONE guard one question. What do you ask?',
    options: [
      '"If I asked the OTHER guard which door is safe, which would he point to?" — then take the OPPOSITE door',
      '"Which door is safe?" — then take that door',
      '"Are you the truth-teller?" — and reason from the answer',
      '"Is the left door safe?" — and invert if the guard lies',
    ],
    optionExplanations: [
      'Correct: both guards report the WRONG door (truth-teller truthfully reports the liar’s wrong answer; liar lies about the truth-teller’s right answer) — so the opposite is safe.',
      'You cannot identify which guard lies, so the answer is untrustworthy.',
      'Both answer "yes", revealing nothing.',
      'Without knowing who lies, inverting is a coin flip.',
    ],
    reasoning: [
      'Ask guard X about the other guard Y: if X is truthful, you get Y’s lie; if X lies, you get the opposite of Y’s truth.',
      'Both cases yield the SAME wrong door — double negation composes.',
      'The trick generalizes: route the question through the unknown to make both branches agree.',
    ],
    hints: ['Ask about the OTHER guard’s answer, not reality directly.', 'Enumerate the two cases: X truthful, X lying.'],
    objectives: ['Compose truth and lies through indirection', 'Enumerate cases exhaustively'],
  }),

  quizChallenge({
    id: 'logic.handshake-count',
    category: 'logic',
    challengeType: 'logic_puzzle',
    difficulty: 'easy',
    minutes: 8,
    concepts: ['combinatorics'],
    tags: ['counting'],
    skills: ['Pair counting'],
    subcategories: ['counting'],
    title: 'The Round of Handshakes',
    subtitle: 'Five people, everyone shakes once.',
    description: 'Count pairwise interactions — the combinatorics behind every "unique pairs" question.',
    question: 'Five people meet and every pair shakes hands exactly once. How many handshakes happen?',
    options: [
      '10',
      '5',
      '20',
      '25',
    ],
    optionExplanations: [
      'Correct: C(5,2) = 5×4/2 = 10.',
      'That is the star count — one person shaking four hands.',
      'That double-counts every handshake.',
      'That counts ordered pairs including self-pairs — neither applies.',
    ],
    reasoning: [
      'Each of 5 people shakes 4 hands: 5 × 4 = 20 endpoints.',
      'Every handshake has two endpoints, so divide by 2 → 10.',
      'Equivalently C(5,2) = 10.',
    ],
    hints: ['Count handshake ENDPOINTS first.', 'Does the person-order matter?'],
    objectives: ['Count unordered pairs', 'Avoid double counting'],
  }),

  quizChallenge({
    id: 'logic.clock-hands',
    category: 'logic',
    challengeType: 'logic_puzzle',
    difficulty: 'intermediate',
    minutes: 12,
    concepts: ['rate problems'],
    tags: ['geometry'],
    skills: ['Angular reasoning'],
    subcategories: ['rates'],
    title: 'The Overlapping Hands',
    subtitle: '3:15 is almost a right angle — almost.',
    description: 'Compute the exact angle between clock hands at 3:15.',
    question: 'What is the exact angle between the hour and minute hands at 3:15?',
    options: [
      '7.5 degrees',
      '0 degrees — both point at 3',
      '15 degrees',
      '30 degrees',
    ],
    optionExplanations: [
      'Correct: the hour hand moves 0.5°/min, so at 15 minutes past 3 it sits at 97.5°; the minute hand is at 90°. Difference: 7.5°.',
      'The hour hand drifts while the minute hand sweeps — they only coincide at ~3:16:22, not 3:15.',
      'That ignores the hour hand’s motion during the 15 minutes.',
      'That is the hour-hand spacing between numerals, not the hand separation.',
    ],
    reasoning: [
      'Minute hand: 6°/min → 15 × 6 = 90°.',
      'Hour hand: 30°/hour = 0.5°/min → 3×30 + 15×0.5 = 97.5°.',
      'Angle = |97.5 − 90| = 7.5°.',
    ],
    hints: ['The hour hand is not frozen at the 3 — it creeps.', 'Degrees per minute: minute hand 6, hour hand 0.5.'],
    objectives: ['Model hands as moving at fixed rates', 'Combine base offsets with drift'],
  }),

  quizChallenge({
    id: 'logic.missing-dollar',
    category: 'logic',
    challengeType: 'logic_puzzle',
    difficulty: 'easy',
    minutes: 10,
    concepts: ['fallacies', 'accounting'],
    tags: ['classic'],
    skills: ['Ledger reasoning'],
    subcategories: ['deduction'],
    title: 'The Missing Dollar',
    subtitle: 'Adding the wrong things to thirty.',
    description: 'Resolve the hotel-bill riddle by fixing the ledger.',
    question:
      'Three guests pay $30 for a room. The clerk realizes the price is $25 and sends $5 back via the bellhop, who pockets $2 and returns $1 to each guest. Each guest paid $9 → 3 × 9 = 27, and the bellhop has $2 → 27 + 2 = 29. Where is the missing dollar?',
    options: [
      'Nowhere: the $27 already includes the bellhop’s $2 ($25 room + $2 pocketed); adding the $2 again is the fallacy',
      'The clerk kept it',
      'Rounding error in the guests’ payments',
      'The puzzle is unsolvable — one dollar genuinely vanishes',
    ],
    optionExplanations: [
      'Correct: the guests’ $27 = $25 (clerk) + $2 (bellhop). The correct check is 27 − 2 = 25, or 25 + 2 + 3 = 30. Adding 27 + 2 adds the bellhop’s cut twice.',
      'The clerk has exactly $25 — consistent with the books.',
      'All amounts are whole dollars; nothing rounds.',
      'The ledger balances perfectly once the correct quantities are summed.',
    ],
    reasoning: [
      'Guest outflow: 3 × 9 = 27.',
      'Where the 27 went: 25 to the clerk + 2 to the bellhop.',
      'The riddle adds the 2 AGAIN to the 27 while forgetting the guests’ $3 refund — a category error, not a math error.',
    ],
    hints: ['Write what each actor holds: clerk, bellhop, guests.', 'Should the bellhop’s $2 be added to the guests’ spending or subtracted from it?'],
    objectives: ['Audit riddles with ledgers', 'Recognize double-counting fallacies'],
  }),

  quizChallenge({
    id: 'logic.coin-stacks',
    category: 'logic',
    challengeType: 'logic_puzzle',
    difficulty: 'hard',
    minutes: 18,
    concepts: ['encoding by weight'],
    tags: ['classic'],
    skills: ['Information packing'],
    subcategories: ['deduction'],
    title: 'The Counterfeit Stack',
    subtitle: 'One weighing, ten suspects.',
    description: 'Identify the fake stack with a single scale reading.',
    question:
      'Ten stacks each hold 10 coins. Genuine coins weigh 10 g; one entire stack is counterfeit at 9.9 g per coin. You have a digital scale and may weigh ONCE. How do you find the counterfeit stack?',
    options: [
      'Take i coins from stack i (1..10), weigh all 55 together: the shortfall in tenths of a gram IS the stack number',
      'Weigh each stack’s first coin — that is ten weighings, but the riddle allows one',
      'Split the stacks into two groups of five and binary-search with three weighings',
      'Weigh all ten full stacks and subtract the genuine weight',
    ],
    optionExplanations: [
      'Correct: all-genuine weight would be 550 g; a shortfall of k × 0.1 g pinpoints stack k, since only k coins came from it.',
      'Uses ten weighings — the constraint is one.',
      'Binary search needs log₂(10) > 3 and does not fit one weighing.',
      'One full-weigh tells you the total shortfall but not WHICH stack contributed it.',
    ],
    reasoning: [
      'The trick encodes the stack INDEX into the COUNT of coins weighed from it.',
      'Shortfall = (number of counterfeit coins on the scale) × 0.1 g, and that number is unique per stack.',
      'This is the general pattern: make each hypothesis produce a distinct observation.',
    ],
    hints: ['How many coins from stack 1? From stack 2? From stack k?', 'What single number does the scale report, and how does it map back?'],
    objectives: ['Encode hypotheses into observations', 'Design one-shot identification schemes'],
  }),

  quizChallenge({
    id: 'logic.brothers-sisters',
    category: 'logic',
    challengeType: 'logic_puzzle',
    difficulty: 'intermediate',
    minutes: 15,
    concepts: ['algebraic modeling'],
    tags: ['algebra'],
    skills: ['System-of-equations modeling'],
    subcategories: ['algebra'],
    title: 'The Family Census',
    subtitle: 'Count siblings from two viewpoints.',
    description: 'Translate two sibling statements into equations and solve.',
    question:
      'In one family: a girl says "I have as many brothers as sisters." One of her brothers says "I have twice as many brothers as sisters." How many boys and girls are in the family?',
    options: [
      '3 boys and 4 girls',
      '4 boys and 3 girls',
      '2 boys and 2 girls',
      '6 boys and 4 girls',
    ],
    optionExplanations: [
      'Correct: girl → B = G − 1; brother → B − 1 = G/2. Solving gives G = 4, B = 3. Check: the girl has 3 brothers and 3 sisters ✓; a boy has 2 brothers and 4 sisters (2 = 4/2) ✓.',
      'That swaps the equations — check the boy’s claim: 3 brothers vs 3 sisters is not "twice as many".',
      'The girl’s statement fails: she would have 2 brothers and 1 sister.',
      'No viewpoint balances: the girl would have 6 brothers and 3 sisters.',
    ],
    reasoning: [
      'From a girl’s view: brothers = B, sisters = G − 1 → B = G − 1.',
      'From a boy’s view: brothers = B − 1, sisters = G, and B − 1 = G/2.',
      'Substitute: G − 2 = G/2 → G = 4 → B = 3.',
      'Always verify both statements against the solution — each equation is one person’s observation.',
    ],
    hints: ['Each speaker counts themselves OUT of one group.', 'Two statements, two unknowns — write both equations before solving.'],
    objectives: ['Model viewpoint-dependent counting', 'Verify solutions against every constraint'],
  }),
];

export const puzzleTemplates: QuestTemplate[] = [
  quizChallenge({
    id: 'puzzle.locker-squares',
    category: 'puzzle',
    challengeType: 'logic_puzzle',
    difficulty: 'hard',
    minutes: 20,
    concepts: ['divisors', 'perfect squares'],
    tags: ['classic'],
    skills: ['Invariant discovery'],
    subcategories: ['patterns'],
    title: 'The Thousand Lockers',
    subtitle: 'Why squares survive the toggling.',
    description: '1000 lockers, 1000 students, and a pattern hiding in the divisors.',
    question:
      '1000 closed lockers line a hall. Student 1 toggles every locker; student 2 toggles every 2nd locker; … student k toggles every k-th locker. After all 1000 students pass, which lockers are open?',
    options: [
      'Exactly the perfect squares: 1, 4, 9, … 961 — 31 lockers, because only squares have an odd number of divisors',
      'Every other locker — 500 open lockers',
      'Only locker 1 and locker 1000',
      'All 1000 are open again — every locker is toggled an even number of times',
    ],
    optionExplanations: [
      'Correct: locker n is toggled once per divisor of n. Divisors pair up (d, n/d) except when d = √n, so squares have odd divisor counts and end open.',
      'Toggling is not uniform — it depends on each number’s divisors.',
      'Every locker is touched by student 1 and by itself at minimum; 1000 itself is not special.',
      'Locker 1 is toggled exactly once (by student 1) — clearly odd, so this claim fails immediately.',
    ],
    reasoning: [
      'Locker n’s final state = parity of its divisor count.',
      'Divisors pair as (d, n/d); the pair d = n/d exists only when n is a perfect square.',
      'Squares up to 1000: 1² through 31² → 31 open lockers.',
    ],
    hints: ['Simulate locker 12 (divisors 1,2,3,4,6,12) and locker 16 (1,2,4,8,16).', 'When does a divisor fail to pair with a different partner?'],
    objectives: ['Reduce simulation to divisor parity', 'Find the invariant behind a pattern'],
  }),

  quizChallenge({
    id: 'puzzle.bridge-torch',
    category: 'puzzle',
    challengeType: 'logic_puzzle',
    difficulty: 'hard',
    minutes: 20,
    concepts: ['scheduling optimization'],
    tags: ['classic'],
    skills: ['Search-space pruning'],
    subcategories: ['scheduling'],
    title: 'The Torchlit Bridge',
    subtitle: 'Seventeen minutes for four travelers.',
    description: 'The classic bridge crossing: the counterintuitive pairing trick.',
    question:
      'Four people must cross a night bridge, two at a time, sharing one torch. Crossing times: 1, 2, 5 and 10 minutes (a pair moves at the slower’s pace). What is the minimum total time?',
    options: [
      '17 minutes: 1+2 cross, 1 returns, 5+10 cross, 2 returns, 1+2 cross',
      '19 minutes: always send 1 as the ferry (1+10, 1 back, 1+5, 1 back, 1+2)',
      '22 minutes: cross slowest pairs first',
      '10 minutes: the fastest person carries the torch for everyone',
    ],
    optionExplanations: [
      'Correct: 2 + 1 + 10 + 2 + 2 = 17 — paying two shuttle trips (1 and 2) so the two slowest cross TOGETHER, hiding the 5 behind the 10.',
      '19 is the intuitive greedy strategy: it makes the 5-minute and 10-minute trips SEPARATELY, paying both.',
      'No ordering of naive pairs reaches 22 as a minimum — but it is certainly not optimal.',
      'Only two may cross at a time; a single shuttle cannot serve four people.',
    ],
    reasoning: [
      'The insight: once the two slowest must both cross, pairing them costs 10 TOTAL instead of 5 + 10 = 15 separately.',
      'To pull that off, the two fastest shuttle the torch back both times.',
      'Verify: forward 2, back 1, forward 10, back 2, forward 2 → 17.',
    ],
    hints: ['The two slowest should cross at the SAME time.', 'Who shuttles the torch back — and how many return trips exist?'],
    objectives: ['Escape greedy framing', 'Prove optimality by accounting for every trip'],
  }),
];
