import { regexChallenge, quizChallenge, type QuestTemplate } from './framework.js';

/**
 * Regex pool — every template declares samples that are run through the real
 * RegExp at generation time. If a pattern does not match what the samples
 * claim, generation fails.
 */

export const regexTemplates: QuestTemplate[] = [
  regexChallenge({
    id: 'regex.anchors',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'easy',
    minutes: 10,
    concepts: ['anchors'],
    tags: ['anchors'],
    skills: ['Anchor semantics'],
    subcategories: ['anchors'],
    title: 'The Anchored Match',
    subtitle: 'Assertions at both ends.',
    description: 'What ^ and $ actually assert, and which strings survive them.',
    mode: 'explain',
    pattern: '^abc$',
    flags: '',
    samples: [
      { text: 'abc', matches: true },
      { text: 'xabc', matches: false },
      { text: 'abcx', matches: false },
      { text: ' abc', matches: false },
      { text: 'ABC', matches: false },
    ],
    question: 'Which of the test strings match `/^abc$/`, and why do the others fail?',
    explanation: [
      '^ asserts the match must start at the beginning of the string (no character consumed).',
      'abc then matches literally, case-sensitively.',
      '$ asserts the string must END right there — so "abcx" fails even though it contains abc.',
      '" xabc" fails at ^ (a space is not a); "ABC" fails case sensitivity — no i flag.',
    ],
    mistakes: [
      'Thinking ^ matches "any line start" by default — with the m flag it does, without it the whole string must comply.',
      'Confusing $ with \\n handling: $ matches just before a final newline in some engines.',
    ],
    hints: [
      'Anchors are zero-width: they assert position, they do not consume characters.',
      'Check both ends of each test string.',
    ],
    objectives: [
      'Use anchors for exact-string validation',
      'Distinguish assertion from consumption',
    ],
  }),

  regexChallenge({
    id: 'regex.digits-plus',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'easy',
    minutes: 8,
    concepts: ['character classes', 'quantifiers'],
    tags: ['quantifiers'],
    skills: ['Class + quantifier reading'],
    subcategories: ['quantifiers'],
    title: 'The Digit Run',
    subtitle: 'One or more, anywhere in the string.',
    description: 'Class-and-quantifier semantics without anchors.',
    mode: 'explain',
    pattern: '\\d+',
    flags: '',
    samples: [
      { text: 'abc', matches: false },
      { text: '123', matches: true },
      { text: 'a1b2', matches: true },
      { text: '', matches: false },
      { text: 'v2.0', matches: true },
    ],
    question: 'Which test strings contain a match for `/\\d+/`?',
    explanation: [
      '\\d is the digit class [0-9]; + requires ONE OR MORE consecutive digits.',
      '"abc" has no digits at all; the empty string cannot satisfy "at least one".',
      '"a1b2" matches the single-digit run "1" — the pattern needs only one run, not the whole string.',
      '"v2.0" matches "2" (the dot is not a digit and does not need to be).',
    ],
    mistakes: [
      'Assuming the pattern must match the ENTIRE string — without anchors, any substring match counts.',
      'Confusing + (one or more) with * (zero or more): \\d* would match "abc" too, via the empty match.',
    ],
    hints: [
      'There are no anchors — a match anywhere is enough.',
      '+ is one-or-more; is one digit enough in "a1b2"?',
    ],
    objectives: ['Read class+quantifier patterns', 'Apply "matches anywhere" semantics'],
  }),

  regexChallenge({
    id: 'regex.write-hex-color',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'intermediate',
    minutes: 15,
    concepts: ['quantifiers', 'character classes'],
    tags: ['validation'],
    skills: ['Writing validation patterns'],
    subcategories: ['validation'],
    title: 'The Hex Validator',
    subtitle: 'Exactly six, after the hash.',
    description: 'Author an anchored validator for six-digit hex colors.',
    mode: 'write',
    pattern: '^#[0-9a-fA-F]{6}$',
    flags: '',
    samples: [
      { text: '#a1b2c3', matches: true },
      { text: '#A1B2C3', matches: true },
      { text: '#12345', matches: false, note: 'too short' },
      { text: 'a1b2c3', matches: false, note: 'missing #' },
      { text: '##a1b2c3', matches: false, note: 'extra #' },
      { text: '#a1b2cg', matches: false, note: 'g is not a hex digit' },
    ],
    question:
      'Write a regular expression that matches exactly six-digit hex color codes: a literal `#` followed by exactly six hex digits (upper or lower case), and nothing else.',
    explanation: [
      '^ anchors the start so "##a1b2c3" cannot sneak an extra # into the match.',
      '# matches the literal hash — no escaping needed (# is not a metacharacter).',
      '[0-9a-fA-F] is the hex digit class; {6} demands exactly six of them.',
      '$ anchors the end, rejecting short and overlong strings alike.',
      '[0-9a-f]{6} with the i flag is equivalent: /^#[0-9a-f]{6}$/i.',
    ],
    alternatives: ['^#[0-9a-f]{6}$ with the i flag', '^#(?:[0-9a-fA-F]{6})$'],
    mistakes: [
      'Forgetting either anchor — "xa1b2c3" would match a substring.',
      'Using {6,} (six or more) instead of exactly {6}.',
    ],
    hints: [
      'Two anchors and one quantifier are all you need.',
      'Which characters belong to the hex alphabet?',
    ],
    objectives: ['Author anchored validation patterns', 'Use bounded quantifiers precisely'],
  }),

  regexChallenge({
    id: 'regex.write-time-hhmm',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'hard',
    minutes: 20,
    concepts: ['alternation', 'grouping'],
    tags: ['validation'],
    skills: ['Range encoding in patterns'],
    subcategories: ['validation'],
    title: 'The Strict Clock',
    subtitle: 'HH:MM with ranges encoded by hand.',
    description: 'Encode numeric ranges character by character in a validator.',
    mode: 'write',
    pattern: '^(?:[01]\\d|2[0-3]):[0-5]\\d$',
    flags: '',
    samples: [
      { text: '00:00', matches: true },
      { text: '09:30', matches: true },
      { text: '23:59', matches: true },
      { text: '24:00', matches: false, note: 'hour out of range' },
      { text: '9:30', matches: false, note: 'hour must be two digits' },
      { text: '12:60', matches: false, note: 'minute out of range' },
      { text: '12:5', matches: false, note: 'minute must be two digits' },
    ],
    question:
      'Write a pattern that validates 24-hour times in strict `HH:MM` form: hours 00–23, minutes 00–59, both always two digits, with a literal colon between.',
    explanation: [
      'Hours: [01]\\d covers 00–19, and 2[0-3] covers 20–23 — alternation joins the two ranges.',
      '(?: … ) groups without capturing; a plain ( … ) would work but wastes a capture slot.',
      'Minutes: [0-5]\\d covers 00–59 exactly.',
      'The two anchors reject "9:30" (missing leading zero) and anything longer.',
    ],
    alternatives: ['^([01][0-9]|2[0-3]):[0-5][0-9]$'],
    mistakes: [
      'Trying \\d{1,2} for the hour — it accepts "9:30" and "29:00".',
      'Forgetting that ranges are per-CHARACTER: [0-23] means 0, 1 or 2 — not the range zero to twenty-three.',
    ],
    hints: [
      'Encode numeric ranges digit by digit: tens place first.',
      'Which two families of hour values exist: 00–19 and 20–23.',
    ],
    objectives: ['Encode numeric ranges in regex', 'Prefer non-capturing groups in validators'],
  }),

  regexChallenge({
    id: 'regex.word-boundary',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'easy',
    minutes: 10,
    concepts: ['word boundaries'],
    tags: ['boundaries'],
    skills: ['Boundary semantics'],
    subcategories: ['anchors'],
    title: 'The Whole Word',
    subtitle: 'Boundaries, not spaces.',
    description: 'Zero-width assertions and the word-character definition.',
    mode: 'explain',
    pattern: '\\bcat\\b',
    flags: '',
    samples: [
      { text: 'cat', matches: true },
      { text: 'a cat', matches: true },
      { text: 'catalog', matches: false },
      { text: 'concatenate', matches: false },
      { text: 'cat.', matches: true },
    ],
    question: 'Which test strings match `/\\bcat\\b/`?',
    explanation: [
      '\\b matches a position between a word character ([A-Za-z0-9_]) and a non-word character (or string edge).',
      '"cat" and "a cat" have word edges on both sides of cat.',
      '"catalog" fails because o follows cat — no boundary there.',
      '"cat." matches: the period is a non-word character, so a boundary exists after t.',
    ],
    mistakes: [
      'Thinking \\b matches a SPACE — it matches a position, and a space is merely one thing that can create it.',
      'Forgetting the underscore is a word character: "my_cat" does NOT match /\\bcat\\b/.',
    ],
    hints: [
      'Boundaries are zero-width positions, not characters.',
      'What counts as a word character: exactly [A-Za-z0-9_].',
    ],
    objectives: ['Use \\b for whole-word matching', 'Explain the word-character definition'],
  }),

  regexChallenge({
    id: 'regex.negated-class',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'easy',
    minutes: 8,
    concepts: ['negated character classes'],
    tags: ['classes'],
    skills: ['Negation reading'],
    subcategories: ['classes'],
    title: 'The Excluded Class',
    subtitle: 'Everything except the digits.',
    description: 'Negated character classes and the two meanings of ^.',
    mode: 'explain',
    pattern: '[^0-9]',
    flags: '',
    samples: [
      { text: 'a1', matches: true },
      { text: '123', matches: false },
      { text: '', matches: false },
      { text: '42a', matches: true },
      { text: '1.5', matches: true },
    ],
    question: 'What does `/[^0-9]/` match, and which test strings contain a match?',
    explanation: [
      'The leading ^ INSIDE a class negates it: [^0-9] is "any single character that is not a digit".',
      '"a1" and "42a" contain a non-digit; "1.5" matches the dot.',
      '"123" is all digits, and the empty string has nothing to match — both fail.',
      'Negated classes still match exactly ONE character per repetition; [^0-9]+ would consume "a" entirely.',
    ],
    mistakes: [
      'Reading ^ at class start as the string-start anchor — meaning flips by position.',
      'Assuming [^0-9] excludes only 0-9 but also excludes punctuation — it includes everything else, dots included.',
    ],
    hints: ['^ has a completely different meaning inside [ ].', 'Is the dot a digit?'],
    objectives: ['Read negated classes correctly', 'Distinguish the two meanings of ^'],
  }),

  regexChallenge({
    id: 'regex.date-groups',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'intermediate',
    minutes: 12,
    concepts: ['groups', 'quantifiers'],
    tags: ['groups'],
    skills: ['Capture group reading'],
    subcategories: ['groups'],
    title: 'The Dated Groups',
    subtitle: 'Four digits, a dash, two more.',
    description: 'Capture groups and exact quantifiers in a date fragment.',
    mode: 'explain',
    pattern: '(\\d{4})-(\\d{2})',
    flags: '',
    samples: [
      { text: '2026-10', matches: true },
      { text: '202-10', matches: false },
      { text: '2026-1', matches: false },
      { text: 'year 2026-10-07', matches: true },
    ],
    question:
      'Which strings match `/(\\d{4})-(\\d{2})/`, and what do the two groups capture in "year 2026-10-07"?',
    explanation: [
      '\\d{4} demands exactly four digits captured into group 1; \\d{2} captures exactly two into group 2.',
      '"202-10" fails (three digits before the dash); "2026-1" fails (one digit after).',
      'Without anchors, the pattern matches anywhere: "year 2026-10-07" matches starting at "2026", group 1 = "2026", group 2 = "10".',
      'The trailing -07 is irrelevant: the pattern is not anchored and stops after the second group.',
    ],
    mistakes: [
      'Assuming the match must cover the whole string — only ^…$ would require that.',
      'Counting {4} as "up to four" — {4} is exactly four; {4,} would be four-or-more.',
    ],
    hints: ['{n} is exact repetition.', 'No anchors means a mid-string match is fine.'],
    objectives: ['Track capture groups through a match', 'Apply exact quantifiers'],
  }),

  regexChallenge({
    id: 'regex.escape-the-dot',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'easy',
    minutes: 8,
    concepts: ['metacharacters', 'escaping'],
    tags: ['escaping'],
    skills: ['Metacharacter discipline'],
    subcategories: ['metacharacters'],
    title: 'The Literal Dot',
    subtitle: 'Escaping the wildcard.',
    description: 'What the backslash protects, and what an unescaped dot costs.',
    mode: 'explain',
    pattern: '\\.',
    flags: '',
    samples: [
      { text: 'a.c', matches: true },
      { text: 'abc', matches: false },
      { text: '...', matches: true },
      { text: '.gitignore', matches: true },
    ],
    question:
      'Which strings contain a match for `/\\./`, and what would happen WITHOUT the backslash?',
    explanation: [
      '\\. matches a literal dot; the backslash strips the special meaning.',
      'Unescaped, . means "any single character except newline" — /a.c/ would then match "abc" too.',
      '"abc" contains no literal dot, so the escaped pattern cannot match it.',
      '"..." and ".gitignore" both contain dots; the pattern matches the first one found.',
    ],
    mistakes: [
      'Over-escaping: /\\.\\./ is two literal dots, not "any two characters".',
      'Escaping inside character classes where . is already literal: [.] works, [\\.] is equivalent but noisy.',
    ],
    hints: [
      'Which regex metacharacter is the wildcard?',
      'Inside a character class, does the dot keep its special meaning?',
    ],
    objectives: [
      'Escape metacharacters deliberately',
      'Predict the wildcard behaviour of an unescaped dot',
    ],
  }),

  quizChallenge({
    id: 'regex.greedy-vs-lazy',
    category: 'regex',
    challengeType: 'regex',
    difficulty: 'intermediate',
    minutes: 12,
    concepts: ['greedy matching', 'lazy quantifiers'],
    tags: ['quantifiers'],
    skills: ['Backtracking behaviour'],
    subcategories: ['quantifiers'],
    title: 'The Greedy Swallow',
    subtitle: 'How far does .* reach?',
    description: 'Greedy vs lazy quantifiers change WHAT a pattern matches, not just whether.',
    scenario: {
      language: 'javascript',
      code: `const text = '<a> and <b>';

text.match(/<(.+)>/)[1];
// → ?

text.match(/<(.*?)>/)[1];
// → ?`,
    },
    question: 'What does each capture group return?',
    options: [
      '"a> and <b" for greedy; "a" for lazy',
      '"a" for greedy; "a> and <b" for lazy',
      'Both return "a"',
      'Both return "a> and <b"',
    ],
    optionExplanations: [
      'Correct: greedy .* expands to the LAST possible > (then backtracks minimally), so group 1 spans "a> and <b"; lazy .*? stops at the FIRST >.',
      'It is the reverse: greedy takes the longest match, lazy the shortest.',
      'The two strategies differ precisely in where they stop.',
      'Only the greedy version reaches that far.',
    ],
    reasoning: [
      'Greedy quantifiers consume as much as possible, then backtrack just enough to complete the match — landing on the final >.',
      'Lazy quantifiers (.+?, .*?) consume as little as possible, expanding only while the rest of the pattern fails.',
      'For tokenizing markup-like text, the lazy form is almost always the intended one.',
    ],
    hints: [
      'Greedy grabs everything, then gives back the minimum.',
      'The lazy suffix is a question mark after the quantifier.',
    ],
    objectives: ['Predict greedy backtracking', 'Choose lazy quantifiers for delimiters'],
  }),
];
